### PR TITLE
add last-item class

### PR DESCRIPTION
**Pull request by mamaretti**

### CODE REVIEW

**Comment by brunjo** [comment]
I wonder what the use case for this is? What are using the class for?

**Comment by mamaretti** [comment]
i use your gallery with an image-zoom-effect when rollover.
when zoom it shows additional infos about the image

when using    transform-origin: center center;
the last and first item will be cropped

see my css below


.item:hover {
    position: relative;
    -webkit-transform: scale(1.4);
    -ms-transform: scale(1.4);
    -o-transform: scale(1.4);
    transform: scale(1.4);
}

.item {
    overflow: hidden;
    z-index: 10;
    -webkit-transition: transform 150ms;
    -o-transition: transform 150ms;
    transition: transform 150ms;
    -webkit-transform-origin: center center;
    -moz-transform-origin: center center;
    -ms-transform-origin: center center;
    transform-origin: center center;
}

.item.first-item, .item.last-row {
    -webkit-transform-origin: left center;
    -moz-transform-origin: left center;
    -ms-transform-origin: left center;
    transform-origin: left center;
}

.item.last-item {
    -webkit-transform-origin: right center;
    -moz-transform-origin: right center;
    -ms-transform-origin: right center;
    transform-origin: right center;
}

**Comment by mamaretti** [comment]
do you plan to merge it in future?

**Comment by mamaretti** [comment]
hi brunjo, can you merge it?

**Comment by brunjo** [comment]
Thanks for the reminder. I'll merge the PR.

**Pull request merged**
